name: image_gallery_saver_plus
description: A Flutter plugin for saving images to the gallery. iOS needs to add the following keys to your Info.plist file.
version: 4.0.1
# publish_to: 'https://pub.dev'  # Publishes to pub.dev (default)
homepage: https://github.com/ArmanKT/image_gallery_saver_plus
repository: https://github.com/ArmanKT/image_gallery_saver_plus

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.image_gallery_saver_plus
        pluginClass: ImageGallerySaverPlusPlugin
      ios:
        pluginClass: ImageGallerySaverPlusPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

# Optional but recommended:
# Add a changelog file and update it with version history.
# A 'CHANGELOG.md' file is necessary for publishing.
